config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'locate' => 'users#locate'
  get 'users/edit'

  resources :users do
    collection do
      get 'search'
    end
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    member do
      put 'like' => 'posts#upvote'
      put 'dislike' => 'posts#downvote'
      get 'my_posts' => 'posts#my_posts'
    end
    resources :comments
  end

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" %>
    <div class="alert red alert-dismissable">
      <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
      &times;
      </button>
      <strong>Error! </strong>The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ol>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field form-group">
  	<%= f.label :avatar, "Upload an image" %>
  	<%= f.file_field :avatar %>
  </div>

  <div class="field form-group">
    <%= f.text_area :content, placeholder: "Compose new post...", class: 'form-control' %>
  </div>

  <%= f.submit "Post", class: "btn btn-primary btn-block" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1 class="user-post"><%= link_to current_user.first_name, current_user %></h1>
<span class="user-post"><%= link_to "View my posts", my_posts_post_path(current_user) %></span>

<span><%= pluralize(current_user.posts.count, "Post") %></span>