config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'locate' => 'users#locate'
  get 'users/edit'

  resources :users do
    collection do
      get 'search'
    end
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    member do
      put 'like' => 'posts#upvote'
      put 'dislike' => 'posts#downvote'
      get 'my_posts' => 'posts#my_posts'
    end
    resources :comments
  end

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 150 }
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "300x300>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :edit, :destroy, :upvote, :downvote, :show, :index]
	before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post Created Successfully!"
			redirect_to root_path
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def show
		@comments = @post.comments
	end

	def edit

	end

	def update
		if current_user.posts.update_all(post_params)
			flash.now[:info] = "Your Post Updated Successfully"
			redirect_to @post
		else
			render 'edit'
		end
	end

	def index
		@posts = Post.paginate(page: params[:page])
	end

	def destroy
		@post.delete
		flash.now[:warning] = "Your Post Deleted Successfully"
		redirect_to root_url
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user
		redirect_to :back
	end

	def my_posts
 		@user = User.find(params[:id])
 		@posts = @user.posts.paginate(page: params[:page])
 	end

	private

		def post_params
			params.require(:post).permit(:content, :avatar)
		end

		def set_post
			@post = Post.find(params[:id])
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<h2><%= link_to post.content, post %></h2>
<% if post.avatar.url != "/avatars/original/missing.png" %>
	<p><%= link_to image_tag(post.avatar.url(:thumb)), post %></p>
<% end %>
Posted <%= time_ago_in_words(post.created_at) %> ago
<div class="btn-group">
	<%= link_to like_post_path(post), method: :put, class: 'btn btn-info btn-sm' do %>
		<span class="glyphicon glyphicon-thumbs-up"></span>
		<%= pluralize(post.get_upvotes.size, 'Like') %>
	<% end %>
	<%= link_to dislike_post_path(post), method: :put, class: 'btn btn-danger btn-sm' do %>
		<span class="glyphicon glyphicon-thumbs-down"></span>
		<%= pluralize(post.get_downvotes.size, 'Dislike') %>
	<% end %>
</div>
<p>
	<% if post.comments.any? %>
		<h4>
			<%= link_to post.comments.last.user do %>
				<%= image_tag(post.comments.last.user.profile_pic.url(:thumb), size: '25x25') %>
			<% end %>
			<%= post.comments.last.content %>
		</h4>
	<% end %>
</p>
<h4><%= link_to "Comment a post", new_post_comment_path(post) %></h4>

app/views/posts/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-1">
		<h1 class="text-center">Edit post</h1>
		<%= render 'shared/post_form' %>
 	</div>
 </div>

app/views/posts/index.html.erb
<% provide(:title, "") %>
<h1>
	All posts
</h1>
<div class="row">
	<div class="col-lg-10 col-lg-offset-2 col-md-9 col-md-offset-1">
		<%= render @posts %>
	</div>
</div>

app/views/posts/my_posts.html.erb
<% provide(:title, "@user.first_name") %>
 <h1>
 	All posts
 </h1>
 <div class="row">
 	<div class="col-lg-10 col-lg-offset-2 col-md-9 col-md-offset-1">
 		<%= render @posts %>
 	</div>
 </div> 

app/views/posts/new.html.erb
<%= render 'shared/post_form' %>

app/views/posts/show.html.erb
<% provide(:title, @post.user.first_name) %>
<h1><%= @post.content %></h1> by <%= link_to @post.user.first_name, user_path(@post.user) %>
<% if @post.avatar.url != "/avatars/original/missing.png" %>
	<p><%= image_tag(@post.avatar.url, class: 'img img-responsive') %></p>
<% end %>
<h6>Posted <%= time_ago_in_words(@post.created_at) %> ago</h6>

<%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-info active' %>
<%= link_to 'Delete Post', @post, method: :delete, data: { confirm: "Are you sure want to delete your post" }, class: 'btn btn-warning active' %>

<h2>Comments</h2>
<div class="container">
	<div class="row">
		<% if @post.comments.any? %>
			<% @post.comments.each do |comment| %>
				<h3>
					<%= link_to comment.user do %>
						<%= image_tag(comment.user.profile_pic.url(:thumb), size: '75x75') %>
					<% end %>
					<%= comment.content %>
				</h3>
				<h6>Commented <%= time_ago_in_words(comment.created_at) %> ago</h6>
				<% if comment.user == current_user %>
					<%= link_to "Edit", edit_post_comment_path(@post, comment), class: 'btn btn-warning btn-xs active' %>
					<%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-xs active' %>
				<% end %>
			<% end %>
		<% else %>
			Be the first person
		<% end %>
	</div>
</div>
<%= link_to "To comment", new_post_comment_path(@post) %>