config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'locate' => 'users#locate'
  get 'users/edit'

  resources :users do
    collection do
      get 'search'
    end
    member do
      get :following, :followers
    end
  end
  
  resources :posts do
    member do
      put 'like' => 'posts#upvote'
      put 'dislike' => 'posts#downvote'
      get 'my_posts' => 'posts#my_posts'
    end
    resources :comments
  end

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer foot">
  <nav>
    <ul>
      <h4 class="black">Follow us on:</h4>
      <li><%= link_to image_tag("facebook.png", alt: "Facebook", size: '40x40'), "https://www.facebook.com", target: "_blank" %></li>
      <li><%= link_to image_tag("twitter.png", alt: "Twitter", size: '40x40'), "https://twitter.com/", target: "_blank" %></li>
      <li><%= link_to image_tag("instagram.png", alt: "Instagram", size: '40x40'), "https://www.instagram.com/", target: "_blank" %></li>
      <li><%= link_to image_tag("pinterest.png", alt: "Instagram", size: '40x40'), "https://www.pinterest.com/", target: "_blank" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CHIRP", root_path, class: 'navbar-brand logo' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">More<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Help', static_pages_help_path %></li>
            <li><%= link_to 'About', static_pages_about_path %></li>
            <li><%= link_to 'Contact Us', static_pages_contact_path, 'data-no-turbolink' => true %></li>
          </ul>
        </li>
        <li>
        <li>    
          <%= form_tag search_users_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for users" %>
            <span class="glyphicon glyphicon-search"></span>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          <% end %>
               
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Locate all users", locate_path, 'data-no-turbolink' => true %></li>
          <li><%= link_to "All users", users_path %></li>
          <li class="dropdown"><%= link_to 'Account<b class="caret"></b>'.html_safe, root_path, class: 'dropdown-toggle', data: { toggle: 'dropdown' } %>
          <ul class="dropdown-menu">
            <li>
              <%= link_to current_user, class: "btn btn-primary" do %>
                <span class="glyphicon glyphicon-info-sign"></span>&nbsp;View profile
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user), class: "btn btn-success" do %>
                <span class="glyphicon glyphicon-lock"></span>&nbsp;Edit profile
              <% end %>
            </li>
            
            <li>
              <%= link_to logout_path, method: :delete, class: "btn btn-warning" do %>
                <span class = "glyphicon glyphicon-log-out"></span>&nbsp;Logout
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
          <li>
            <%= link_to new_user_path do %>
              <span class = "glyphicon glyphicon-user"></span>&nbsp;Sign Up
            <% end %>
          </li>
          <li>
            <%= link_to login_path do %>
              <span class = "glyphicon glyphicon-log-in"></span>&nbsp;Sign In
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag("favicon.ico") %>
  <title><%= full_title(yield(:title)) %></title>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> -->
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="bg"></div>
  <%= render 'layouts/header' %>
  <div class="container content">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |msg_type, msg| %>
          <div class="alert alert-<%= msg_type %> text-center">
            <%= msg %>
          </div>
        <% end %>
        
        <%= yield %>
       
        <%= render 'layouts/footer' %>
      </div>
    </div>
  
  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>